### ISSUE TITLE
Refreshing from header not working

### ISSUE THREAD

**Issue by kostek00** [revilheart/ESGST#387] opened 2017-08-29 15:43 UTC
"Refresh all pages" isn't refreshing anything in whishlist ga (don't know if anywhere else also). I need to refresh whole page.

And "refresh current page" takes so long that I don't if it's working (waited like 10 minutes and it still was going).

I'm using Firefox with tempermokney. It stopped working since you added second refresh icon.

**Comment by revilheart** [comment] 2017-08-29 17:08
Are there errors in the console (Ctrl + Shift + J)?

**Comment by revilheart** [comment] 2017-08-29 21:13
Check if it still happens in the latest version, I found nothing wrong in the code, and without errors in the console, I have no idea what could be happening.

**Comment by kostek00** [comment] 2017-08-30 11:37
Still not working :/

**Comment by revilheart** [comment] 2017-08-30 16:56
Are you using Firefox Containers? The script doesn't work 100% with that.

**Comment by kostek00** [comment] 2017-08-30 17:04
I don't.

**Comment by revilheart** [comment] 2017-08-30 17:08
I'll see if I can find some time today or tomorrow to use Firefox and test it myself so I can try to reproduce it.

**Comment by revilheart** [comment] 2017-09-02 18:39
Just tested on Firefox, and there is actually an error in the console (you probably weren't able to see it because it has to be in the Ctrl + Shift + J console, not the Ctrl + Shift + I one. And I believe errors only appear if the console is open while you try to refresh, not if you open it afterwards. Working on it...

**Comment by revilheart** [comment] 2017-09-02 19:11
Should be fixed.

**Closed by revilheart** 2017-09-02 19:11 UTC
Labels: Bug

**Comment by kostek00** [comment] 2017-09-02 22:24
So that's why I didn't see error.

Yes it's working now. Thank you.
