### ISSUE TITLE
[Bug] Wrong button when I hover ESGST encrypted giveaways button

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#140] opened 2017-06-05 20:13 UTC
When I hover the ESGST encrypted giveaways button, it changes to a button with just two rounded corners. All four corners should be rounded like Trades button.

![2017-06-05_220758](https://cloud.githubusercontent.com/assets/2397851/26801136/32256ab0-4a3c-11e7-94bf-cf975bf80ec9.png)

**Comment by SquishedPotatoe** [comment] 2017-06-07 18:44
@gizellos That is caused by redundant code left in [SGLinkies](https://greasyfork.org/en/scripts/12217-sglinkies/code) from when steamgifts had a FAQ button without a dropdown.

**Comment by gizellos** [comment] 2017-06-14 16:20
The same issue with the giveaway bookmarks button.

**Comment by revilheart** [comment] 2017-06-14 16:38
If it's from another script I can't do anything about it, so closing it.

**Closed by revilheart** 2017-06-14 16:38 UTC
Labels: invalid
