### ISSUE TITLE
Turning off User-Defined Tags is not working for me

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#291] opened 2017-07-27 14:45 UTC
I disabled User-Defined Tags before a week or two and I still can see the tags. I am not sure if it is a bug or I have to wait some more time but I would like you to make it in a way when it works immediately.

I think I already talked about this once and you said me to temporary changed something directly in the script (to force it update). But I don't remember what to change and I think it should be easily done also somewhere in the script settings. I also tried to delete some data but it didn't help.

**Comment by revilheart** [comment] 2017-07-28 14:29
It's because when you enable it, the user-defined tags are saved together with genres, so when you disable it, they're still there, as it's not currently possible to separate them.

**Comment by gizellos** [comment] 2017-07-28 14:38
I see. But deleting some data in Manage Data feature should fix it for me, shouldn't it? Which data exactly?

**Comment by revilheart** [comment] 2017-07-28 14:41
Game Categories data. Although currently it will also delete bundled, owned, wishlisted and ignored that, so you will have to sync again after deleting. I'll change that later.

**Comment by gizellos** [comment] 2017-07-28 14:53
Ok, thanks. Unfortunately, then I am afraid that the switch for user-defined tags is not working. It downloads all the tags and genres again and shows them both even if I have the tags disabled. I tried this before and now and was the same.

**Comment by revilheart** [comment] 2017-07-28 23:44
The bug should be fixed.

**Comment by gizellos** [comment] 2017-07-29 06:52
Nice. Thanks for all your work today or yesterday. :)

**Comment by revilheart** [comment] 2017-08-14 17:19
Should now work as intended.

**Closed by revilheart** 2017-08-14 17:19 UTC
Labels: Bug, Enhancement

**Comment by gizellos** [comment] 2017-08-14 17:21
Cool, thanks. :)
