### ISSUE TITLE
It shows chance to win even before the GAs are created

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#201] opened 2017-06-27 12:26 UTC
Sorry I am not sure if this is already posted here or not. I noticed that it shows chance to win 100 % in the giveaway preview window. I think it is not supposed to be there. And it has red color which is strange.

![2017-06-27_132732](https://user-images.githubusercontent.com/2397851/27587406-9a569f1e-5b44-11e7-99a6-5a6df70fb0af.png)

**Comment by ldeman** [comment] 2017-06-27 13:38
+1 that's a pretty recent change i noticed as well and i'm pretty sure hasn't been reported.
![image](https://user-images.githubusercontent.com/10275898/27590311-ea1b53e0-5b13-11e7-847e-7560adb5805f.png)

**Comment by revilheart** [comment] 2017-06-27 14:08
Weird, that's not appearing for me.

**Comment by ldeman** [comment] 2017-06-27 14:46
yes latest version, it's on the review page of creation.  (create a gift GA and review, just don't confirm)
![image](https://user-images.githubusercontent.com/10275898/27593707-705d940a-5b1d-11e7-904d-fe24adef11c1.png)

**Comment by revilheart** [comment] 2017-06-27 15:11
Yeah, I'm not getting it. Wonder if may be some feature that I have enabled that you guys don't.

**Comment by ldeman** [comment] 2017-06-27 15:21
well it's not related to ratio being disabled because that does it also.  still testing....
![image](https://user-images.githubusercontent.com/10275898/27595412-398ee4ec-5b22-11e7-94e1-a136bfffffce.png)

**Comment by ldeman** [comment] 2017-06-27 15:50
i cant find and enabled/disabled settings that will make it go away.  but there are a lot of combinations.

**Comment by revilheart** [comment] 2017-07-31 20:33
Is this still an issue?

**Comment by gizellos** [comment] 2017-08-01 13:13
Yep, I saw it a minute ago.

**Comment by ldeman** [comment] 2017-08-01 14:34
i rarely review giveaways anymore, but yes it is still there for me when i do review as well.

**Comment by revilheart** [comment] 2017-08-01 15:42
Now it should be fixed.

**Closed by revilheart** 2017-08-01 15:42 UTC
Labels: Bug

**Comment by ldeman** [comment] 2017-08-01 16:27
confirmed.  ^^
thanks
