### ISSUE TITLE
[Bug] Moving elements in giveaways with long descriptions

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#117] opened 2017-05-24 14:21 UTC
When I scroll down a giveaway with long description, the main content div moves to the left. Check the gif.

![moving element](https://cloud.githubusercontent.com/assets/2397851/26408054/123d7efc-409d-11e7-91cc-372e130ddd94.gif)

**Comment by SquishedPotatoe** [comment] 2017-06-07 19:25
Caused by sidebar changing width after offset was calculated.

**Comment by revilheart** [comment] 2017-06-27 13:59
Should be fixed.

**Closed by revilheart** 2017-06-27 13:59 UTC
Labels: Style
