### ISSUE TITLE
[Bug] Comment history - time with the link to the comment

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#135] opened 2017-05-29 16:36 UTC
There is missing time with the link to the comment after the word **at.**

![2017-05-29_181557](https://cloud.githubusercontent.com/assets/2397851/26556862/65afcf00-449d-11e7-8ddc-da0249beef2c.png)

Anyway, the list doesn't look very well. I would love if it looked similar to the normal SG Messages. It would be better and mainly there would be also the text.

**Comment by revilheart** [comment] 2017-06-09 23:42
I don't think that comment can be recovered, it appears there was a problem while saving it, but I can't reproduce it. This feature has been upgraded, so hopefully it doesn't happen anymore.

**Comment by gizellos** [comment] 2017-06-10 00:11
It didn't show the time with any comments. But it doesn't matter anymore since the new version of t he feature is much better and it seems to be working correctly. Thanks.

**Comment by revilheart** [comment] 2017-06-10 01:11
Great, closing this then.

**Closed by revilheart** 2017-06-10 01:11 UTC
Labels: bug
